In [1]:
!pip install numpy

In [2]:
import numpy as np

# 1D Array(Vector):-

In [26]:
a=np.array([2,4,6,8,10])
a

array([ 2,  4,  6,  8, 10])

In [4]:
print(a)

[ 2  4  6  8 10]


# 2D Array(Matrix)

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3D Array(Tensor):-

In [6]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [7]:
print(a)

[ 2  4  6  8 10]


In [8]:
a

array([ 2,  4,  6,  8, 10])

# change datatype:-

In [12]:
a=np.array([ 2,  4,  6,  8, 10],dtype=float)
print(a)

[ 2.  4.  6.  8. 10.]


In [14]:
a=np.array([2,4,6,8,10],dtype=bool)
print(a)

[ True  True  True  True  True]


# Arrange():-

In [18]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [22]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Reshape():-

In [23]:
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
np.arange(1,11,1).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
np.arange(1,25,1).reshape(2,2,2,3)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

# Ones Array:-


In [28]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Zeros Array:-

In [29]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Linspace:-

In [33]:
np.linspace(3,10,6)

array([ 3. ,  4.4,  5.8,  7.2,  8.6, 10. ])

# Identity:-

In [32]:
np.identity((3),dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])