In [1]:
import numpy as np

In [9]:
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
a1=np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# ndim:-Array type (1d,2d)

In [7]:
print(a.ndim)
print(a1.ndim)

1
2


# Shape:- kintne by ka kitna hai

In [10]:
print(a.shape)
print(a1.shape)

(5, 2)
(3, 4)


# Size:- Total number of array in present

In [11]:
print(a.size)
print(a1.size)

10
12


# ItemSize:-size of each element in byte 

In [12]:
print(a.itemsize)
print(a1.itemsize)

4
4


# Dtype:-

In [13]:
print(a.dtype)
print(a1.dtype)

int32
int32


In [14]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
y=np.arange(12,24).reshape(3,4)
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
x+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [17]:
x+y

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [18]:
x-y

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [19]:
x*y

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [21]:
x/y

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [22]:
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
y>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
y[y>15]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [25]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [29]:
x[x%2==0].reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# Random:- print any random Value


In [34]:
t=np.random.random((3,3))*100
t

array([[41.1482219 , 38.40150264, 26.8154014 ],
       [14.69245952,  6.96793988, 16.24703546],
       [92.64693778, 94.45869359, 35.14310331]])

# Round:-

In [36]:
t=np.round(t)
t

array([[41., 38., 27.],
       [15.,  7., 16.],
       [93., 94., 35.]])

In [39]:
t=np.array(t,dtype=int)
t

array([[41, 38, 27],
       [15,  7, 16],
       [93, 94, 35]])

# MAX:-

In [40]:
t.max()

94

# Axis:-

In [45]:
t.max(axis=0)

array([93, 94, 35])

In [46]:
t.max(axis=1)

array([41, 16, 94])

# Sum:-

In [43]:
t.sum()

366

In [47]:
t.sum(axis=0)

array([149, 139,  78])

In [48]:
t.sum(axis=1)

array([106,  38, 222])

# multiply/Produuct :-

In [53]:
np.prod(t)

-1991181760

In [54]:
np.prod(t,axis=0)

array([57195, 25004, 15120])

In [55]:
np.prod(t,axis=1)

array([ 42066,   1680, 305970])

# Statstics Methods :-

In [56]:
np.mean(t)

40.666666666666664

In [58]:
np.median(t)

35.0

In [59]:
np.var(t)

912.2222222222222

In [60]:
np.std(t)

30.203016773531452

# Trignometric :-

In [61]:
np.sin(t)

array([[-0.15862267,  0.29636858,  0.95637593],
       [ 0.65028784,  0.6569866 , -0.28790332],
       [-0.94828214, -0.24525199, -0.42818267]])

In [62]:
np.cos(t)

array([[-0.98733928,  0.95507364, -0.29213881],
       [-0.75968791,  0.75390225, -0.95765948],
       [ 0.3174287 ,  0.96945937, -0.90369221]])

# Floor and Ceil :-

In [64]:
q=np.random.random((2,3))*100
q

array([[ 8.75149212, 53.49702427, 15.34264505],
       [77.64214706, 68.39444686, 56.80636375]])

In [66]:
np.floor(q)

array([[ 8., 53., 15.],
       [77., 68., 56.]])

In [68]:
np.ceil(q)

array([[ 9., 54., 16.],
       [78., 69., 57.]])

Change Row TO Column And column to row

In [71]:
t

array([[41, 38, 27],
       [15,  7, 16],
       [93, 94, 35]])

In [72]:
t.T

array([[41, 15, 93],
       [38,  7, 94],
       [27, 16, 35]])