In [3]:
import numpy as np

# Indexing:-

In [12]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
c=np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
##var_name[indexing_number]
a[7]

7

In [19]:
a[6]

6

In [20]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b[1,1]

5

In [22]:
b[2,3]

11

In [23]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
c[0,1,1]

3

In [25]:
c[1,1,1]

7

In [26]:
c[1,1,0]

6

# Slicing:-

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
1D Array:-
    var_name[Start:End:step]

In [32]:
a[3:9:1]

array([3, 4, 5, 6, 7, 8])

In [33]:
a[:9:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [37]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [48]:
arr[:,2]

array([ 3,  7, 11])

In [49]:
arr[1,:]

array([5, 6, 7, 8])

In [53]:
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [57]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [62]:
arr[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [63]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b[0,::]

array([0, 1, 2, 3])

In [66]:
b[0:2,2]

array([2, 6])

In [70]:
b[2,2:]

array([10, 11])

In [72]:
b[1:,0]

array([4, 8])

In [74]:
b[0:1,1:3]

array([[1, 2]])

In [9]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
c[0]

array([[0, 1],
       [2, 3]])

In [13]:
c[0:1,1:1,1:0]

7

In [16]:
x=np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
x[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
y=np.arange(24).reshape(6,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
y[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
y[[0,5],0::3]

array([[ 0,  3],
       [20, 23]])

In [41]:
y[[3,4],1:3]

array([[13, 14],
       [17, 18]])

In [42]:
y[[2,3],2:]

array([[10, 11],
       [14, 15]])

In [44]:
y[[1,2],1:3]

array([[ 5,  6],
       [ 9, 10]])

In [45]:
y%2==0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [46]:
y[y%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [48]:
y[y>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [51]:
y[(y%2==0) & (y>7)]

array([ 8, 10, 12, 14, 16, 18, 20, 22])