In [1]:
import numpy as np


In [3]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b=np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
print(a+b)

[[ 6  8 10]
 [12 14 16]]


In [16]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)

In [17]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b

array([[0, 1, 2]])

In [19]:
print(a+b)

[[0 2 4]
 [3 5 7]]


In [26]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
b=np.arange(3).reshape(1,3)
b

array([[0, 1, 2]])

In [28]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [29]:
a=np.arange(3).reshape(3,1)
a

array([[0],
       [1],
       [2]])

In [30]:
b=np.arange(3).reshape(1,3)
b

array([[0, 1, 2]])

In [31]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [32]:
a=np.arange(3).reshape(3,1)
a

array([[0],
       [1],
       [2]])

In [35]:
b=np.arange(4).reshape(1,4)
b

array([[0, 1, 2, 3]])

In [36]:
print(a+b)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [41]:
a=np.array([1])
a

array([1])

In [39]:
b=np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [42]:
print(a+b)

[[1 2]
 [3 4]]


In [43]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [46]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
b=np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [48]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

# Ravel():-

In [49]:
a=np.arange(12).reshape(1,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [59]:
a.ndim

3

In [60]:
t=a.ravel()
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
t.ndim

1

# Stacking:- 

In [62]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
y=np.arange(12,24).reshape(3,4)
y

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
np.stack((x,y))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
np.vstack((x,y))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
np.hstack((x,y))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [79]:
np.dstack((x,y))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [73]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
np.column_stack((x,y))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [82]:
np.row_stack((x,y))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# spliting():-

In [88]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [89]:
np.split(a,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [94]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
np.hsplit(x,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [97]:
np.vsplit(x,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Numpy VS Python:-

In [99]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c= []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
end = time.time()
print(end-start)

5.247947692871094


In [100]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
import time
start = time.time()
c = a+b
end = time.time()
print(end-start)

0.12503910064697266
