In [4]:
import numpy as np

# Create Function in numpy

In [5]:
def sigmoid_fn(array):
      return 1+(1+np.exp(-(array)))

In [6]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
sigmoid_fn(a)

array([3.        , 2.36787944, 2.13533528, 2.04978707, 2.01831564,
       2.00673795, 2.00247875, 2.00091188, 2.00033546, 2.00012341])

In [8]:
def si(p,r,t):
    return (p*r*t)/100


In [9]:
si(1000,10,1)

100.0

In [10]:
a=np.random.randint(1,50,10)
a

array([48, 13,  8,  8, 33, 20, 23, 45, 21,  6])

# Sort():-

In [11]:
np.sort(a)

array([ 6,  8,  8, 13, 20, 21, 23, 33, 45, 48])

In [12]:
np.sort(a)[::-1]


array([48, 45, 33, 23, 21, 20, 13,  8,  8,  6])

In [13]:
b=np.random.randint(1,100,35).reshape(5,7)
b

array([[92, 68,  7, 58, 53, 94, 46],
       [66, 42, 80, 15, 40, 26, 61],
       [14, 28, 31, 65, 48, 82, 85],
       [49, 65, 30, 68, 97,  9, 37],
       [56,  5, 91, 96, 96, 97,  1]])

In [17]:
np.sort(b)

array([[10, 19, 19, 29, 36, 67, 84],
       [ 5, 25, 26, 64, 65, 79, 90],
       [12, 15, 32, 40, 44, 71, 87],
       [12, 30, 55, 56, 59, 62, 86],
       [ 1, 14, 38, 55, 62, 92, 93]])

In [18]:
np.sort(b,axis=0)

array([[15, 10, 12, 14, 12,  1, 25],
       [19, 26, 19, 55, 29,  5, 40],
       [30, 44, 62, 64, 62, 32, 55],
       [38, 86, 79, 71, 87, 36, 56],
       [65, 93, 92, 84, 90, 59, 67]])

In [19]:
np.sort(b,axis=1)

array([[10, 19, 19, 29, 36, 67, 84],
       [ 5, 25, 26, 64, 65, 79, 90],
       [12, 15, 32, 40, 44, 71, 87],
       [12, 30, 55, 56, 59, 62, 86],
       [ 1, 14, 38, 55, 62, 92, 93]])

In [14]:
a

array([48, 13,  8,  8, 33, 20, 23, 45, 21,  6])

# Append():-

In [15]:
np.append(a,50)

array([48, 13,  8,  8, 33, 20, 23, 45, 21,  6, 50])

In [19]:
a[3]=8
a

array([ 48,  13,   8,   8, 100,  20,  23,  45,  21,   6])

# Concatenate():-

In [20]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
y=np.arange(6,12).reshape(2,3)
y

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.concatenate((x,y))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np