In [1]:
import numpy as np

C:\Users\hp\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
def sigmoid_fn(array):
    return 1/(1+np.exp(-(array)))

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
sigmoid_fn(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [3]:
def si(p,r,t):
    return (p*r*t)/100

In [4]:
si(1000,2,3)

60.0

In [7]:
a= np.random.randint(1,100,15)
a

array([70, 26, 19, 27,  7, 80, 51, 15, 17, 63, 58, 86, 14,  9, 32])

In [8]:
np.sort(a)

array([ 7,  9, 14, 15, 17, 19, 26, 27, 32, 51, 58, 63, 70, 80, 86])

In [9]:
np.sort(a)[::-1]

array([86, 80, 70, 63, 58, 51, 32, 27, 26, 19, 17, 15, 14,  9,  7])

In [10]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[11,  2, 64,  9],
       [34, 96, 88, 12],
       [65, 70, 18, 62],
       [92, 25, 20, 44],
       [ 4, 37, 10, 48],
       [67, 21, 49, 90]])

In [11]:
np.sort(b)

array([[ 2,  9, 11, 64],
       [12, 34, 88, 96],
       [18, 62, 65, 70],
       [20, 25, 44, 92],
       [ 4, 10, 37, 48],
       [21, 49, 67, 90]])

In [12]:
np.sort(b,axis=0)

array([[ 4,  2, 10,  9],
       [11, 21, 18, 12],
       [34, 25, 20, 44],
       [65, 37, 49, 48],
       [67, 70, 64, 62],
       [92, 96, 88, 90]])

In [13]:
np.sort(b,axis=1)

array([[ 2,  9, 11, 64],
       [12, 34, 88, 96],
       [18, 62, 65, 70],
       [20, 25, 44, 92],
       [ 4, 10, 37, 48],
       [21, 49, 67, 90]])

In [14]:
a

array([70, 26, 19, 27,  7, 80, 51, 15, 17, 63, 58, 86, 14,  9, 32])

In [15]:
np.append(a,100)

array([ 70,  26,  19,  27,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32, 100])

In [16]:
a[3] = 100

In [17]:
a

array([ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32])

In [18]:
b

array([[11,  2, 64,  9],
       [34, 96, 88, 12],
       [65, 70, 18, 62],
       [92, 25, 20, 44],
       [ 4, 37, 10, 48],
       [67, 21, 49, 90]])

In [19]:
b.shape

(6, 4)

In [20]:
b.shape[0]

6

In [21]:
b.shape[1]

4

In [22]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
y = np.arange(6,12).reshape(2,3)
y

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.concatenate((x,y),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [28]:
a

array([ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32])

In [29]:
np.unique(a)

array([  7,   9,  14,  15,  17,  19,  26,  32,  51,  58,  63,  70,  80,
        86, 100])

In [30]:
a

array([ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32])

In [31]:
a.shape

(15,)

In [32]:
np.expand_dims(a,axis=0)

array([[ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
          9,  32]])

In [33]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [34]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [35]:
##where:-
a[a%2==0]

array([ 70,  26, 100,  80,  58,  86,  14,  32])

In [38]:
a

array([ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32])

In [36]:
np.where(a%2==0)

(array([ 0,  1,  3,  5, 10, 11, 12, 14], dtype=int64),)

In [37]:
a[np.where(a%2==0)]

array([ 70,  26, 100,  80,  58,  86,  14,  32])

In [39]:
np.argmax(a)

3

In [40]:
np.argmin(a)

4

In [41]:
np.argsort(a)

array([ 4, 13, 12,  7,  8,  2,  1, 14,  6, 10,  9,  0,  5, 11,  3],
      dtype=int64)

In [42]:
a[np.argmin(a)]

7

In [43]:
q = np.array([1,2,3,np.nan,4,np.nan,7])
q

array([ 1.,  2.,  3., nan,  4., nan,  7.])

In [44]:
np.isnan(q)

array([False, False, False,  True, False,  True, False])

In [45]:
q[np.isnan(q)]

array([nan, nan])

In [47]:
q[~np.isnan(q)]

array([1., 2., 3., 4., 7.])

In [48]:
sachin_tend = np.random.randint(1,100,10)
sachin_tend

array([97, 48, 64, 70, 29, 93, 86, 72,  2, 98])

In [49]:
sachin_tend[0] + sachin_tend[1] + sachin_tend[2] + sachin_tend[3] + sachin_tend[4]

308

In [50]:
np.cumsum(sachin_tend)

array([ 97, 145, 209, 279, 308, 401, 487, 559, 561, 659])

In [51]:
np.cumsum(sachin_tend)[4]

308

In [52]:
np.cumprod(sachin_tend)

array([        97,       4656,     297984,   20858880,  604907520,
        421824512, 1917169664,  597262336, 1194524672, 1099300864])

In [53]:
a

array([ 70,  26,  19, 100,   7,  80,  51,  15,  17,  63,  58,  86,  14,
         9,  32])

In [54]:
np.isin(a,[70,19,100])

array([ True, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [55]:
a[np.isin(a,[70,19,100])]

array([ 70,  19, 100])

In [56]:
a[~np.isin(a,[70,19,100])]

array([26,  7, 80, 51, 15, 17, 63, 58, 86, 14,  9, 32])

In [57]:
np.put(a,[1,5,7],[200,300,400])
a

array([ 70, 200,  19, 100,   7, 300,  51, 400,  17,  63,  58,  86,  14,
         9,  32])

In [59]:
np.delete(a,[1,2,3])

array([ 70,   7, 300,  51, 400,  17,  63,  58,  86,  14,   9,  32])

In [60]:
np.clip(a,a_min=30,a_max=60)

array([60, 60, 30, 60, 30, 60, 51, 60, 30, 60, 58, 60, 30, 30, 32])

In [61]:
a

array([ 70, 200,  19, 100,   7, 300,  51, 400,  17,  63,  58,  86,  14,
         9,  32])

In [62]:
np.flip(a)

array([ 32,   9,  14,  86,  58,  63,  17, 400,  51, 300,   7, 100,  19,
       200,  70])